In [1]:
import cv2
import urllib.request
import numpy as np

stream = urllib.request.urlopen('http://192.168.73.73:8080/?action=stream&ignored.mjpg')
bytes = bytes()

In [2]:
def rgb2mono(rgb):
    r, g, b = rgb[:,:,0], rgb[:,:,1], rgb[:,:,2]
    # mono = 0.2989 * r + 0.5870 * g + 0.1140 * b
    mono = 0.5 * r + 0.25 * g + 0.25 * b
    return mono

In [3]:
while True:
    bytes += stream.read(1024)
    a = bytes.find(b'\xff\xd8')
    b = bytes.find(b'\xff\xd9')
    if a != -1 and b != -1:
        jpg = bytes[a:b+2]
        bytes = bytes[b+2:]
        i = cv2.imdecode(np.fromstring(jpg, dtype=np.uint8), cv2.IMREAD_COLOR)
        i = rgb2mono(i)
        print(i)
#         cv2.imshow('i', i)

D:\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:8: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


[[163.25 138.75 125.75 ... 220.25 220.25 219.25]
 [100.   101.75 111.75 ... 218.   219.   217.25]
 [ 95.75  97.75 109.75 ... 215.75 217.   216.25]
 ...
 [226.   235.   242.   ... 228.5  223.5  217.5 ]
 [221.   228.   236.   ... 226.5  223.5  216.5 ]
 [218.   223.   230.25 ... 223.5  220.5  216.25]]
[[162.25 138.75 124.   ... 220.   220.   218.25]
 [101.25 101.75 110.75 ... 220.   218.75 217.75]
 [ 95.75  99.75 110.   ... 217.75 217.75 216.  ]
 ...
 [226.   235.   241.25 ... 228.5  222.5  217.5 ]
 [221.   229.   236.25 ... 226.5  222.5  215.5 ]
 [217.   224.   230.25 ... 224.5  220.5  215.5 ]]
[[162.   138.25 124.75 ... 221.5  221.   221.  ]
 [ 99.   101.25 110.75 ... 219.   218.75 218.75]
 [ 95.    98.75 109.75 ... 216.75 217.75 217.75]
 ...
 [225.25 233.25 241.25 ... 229.5  225.5  218.25]
 [220.25 229.   236.25 ... 226.5  223.5  216.25]
 [217.   223.   230.25 ... 222.5  219.5  215.  ]]
[[161.   138.25 124.   ... 220.5  222.25 221.25]
 [ 99.   101.75 110.75 ... 220.   219.   220.  ]
 [

[[163.25 137.75 124.75 ... 221.   221.5  220.5 ]
 [100.5  101.75 111.75 ... 219.   219.   220.  ]
 [ 96.5   98.75 109.75 ... 217.   217.   217.25]
 ...
 [224.75 233.5  241.5  ... 228.5  224.5  216.5 ]
 [220.5  228.5  234.75 ... 226.5  222.5  214.5 ]
 [218.5  222.75 229.75 ... 222.5  220.5  215.25]]
[[163.25 138.75 124.5  ... 220.   221.   219.5 ]
 [101.25 102.75 112.5  ... 219.   220.   219.  ]
 [ 96.5   99.5  109.5  ... 217.   218.5  216.5 ]
 ...
 [225.25 233.25 240.5  ... 230.25 224.75 217.5 ]
 [220.25 228.25 235.25 ... 226.5  222.5  215.5 ]
 [216.25 222.25 230.25 ... 221.5  218.5  217.5 ]]
[[162.25 139.25 125.25 ... 219.25 220.25 220.25]
 [100.25 101.25 112.25 ... 218.   218.   218.25]
 [ 95.25  99.25 110.5  ... 216.   217.   217.25]
 ...
 [225.25 233.25 240.25 ... 229.25 225.25 218.25]
 [219.25 227.25 235.25 ... 227.25 224.25 215.5 ]
 [216.25 222.25 230.25 ... 225.5  220.5  215.5 ]]
[[163.25 139.25 124.5  ... 220.25 221.   220.  ]
 [102.25 103.25 111.5  ... 217.   218.   219.  ]
 [

KeyboardInterrupt: 